### ISSUE TITLE
light theme from spyder for vscode

### ISSUE THREAD

**Issue by seyeeet** [Educorreia932/Oblivion-Theme#1]
Hey @Educorreia932 
I see you made dark theme of spyder in vscode.
Can you please also provide the Light one available or tell me how I can do that my self? :) 
Thanks

**Comment by Educorreia932** [comment]
Hey @seyeeet 

I don't intend to make a light version of the theme, since I don't use it myself.
However, to create a Visual Studio theme you can use this [website](https://themes.vscode.one/)
Then you can download your theme as a JSON file and install it following this [tutorial](https://code.visualstudio.com/api/extension-guides/color-theme#create-a-new-color-theme).
